### ISSUE TITLE
Change docs to use Signavio theme

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#106]
In a separate `signavio-workflow` branch, switch to a new theme.

**Comment by SilentGert** [comment]
Is there already a Signavio theme available?

**Comment by hilton** [comment]
Well, the app has the theme that https://app.effektif.com/signavio/ uses, although I don’t know if I can use that locally. There’s no theme for the docs yet, as far as I know.

**Comment by SilentGert** [comment]
I'm talking about the theme for the docs. Currently, they use this one: https://github.com/effektif/sphinx_rtd_theme

**Comment by wolfsoe** [comment]
We got the Signavio manual theme, I uploaded it to google and gave you guys access: https://drive.google.com/open?id=0B5BuFaQWSNboRUFtZW50S1ZWNk0 

However, Timmi is currently updating the theme (longer term project) and might have some valuable insights on that. I can ask him on Wednesday when he is back in Tromsö. 

I think the Effektif manual should not have exactly the same theme as Signavio because it could be confusing for people who use both apps - also, maybe we could link the manuals reciprocally?

**Comment by SilentGert** [comment]
Currently, the theme is added by referencing a specific commit in our theme repository. I would prefer to do it in the same fashion instead of adding the static theme files to our documentation repository. For one, we need to do the same in the admin docs and, furthermore, if it is forked from the original theme repo, you can get updates from them as well.
