### ISSUE TITLE
Refactor links to workflow.signavio.com

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#146]
Soon, there will be two Signavio Workflow SaaS instances:
- [workflow-usa.signavio.com](workflow-usa.signavio.com) (or similar) for the Americas (I suppose).
- [workflow.signavio.com](workflow.signavio.com) (or similar) for everything else.

Once these instances are live, I'll adjust all references to workflow.signavio.com, for example like this:

   _Then use the page [purchasing](https://workflow.signavio.com/buy) ([NCSA](https://workflow-usa.signavio.com/buy))._

@hilton Does a more elegant alternative come to your mind?

**Comment by hilton** [comment]
’NCSA’ isn’t the right acronym, because that means [something else](https://en.wikipedia.org/wiki/NCSA) - only ‘US’ or ‘USA’ would be recognisable in that context.

Marketing regions like ‘the Americas’ are too broad to be generally recognisable, so it’s best to refer to the server location, which is the US. At least there aren’t that many product links, and I guess this doesn’t matter for registration, for example.

**Comment by TimKam** [comment]
thanks, I suppose I go with 'US server', respectively 'German server' then, to avoid any confusion.

**Comment by hilton** [comment]
‘Europe server’ might be better than ‘German server’
