### ISSUE TITLE
Duplicate file output/search hits due to `..include` directive

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#160]
The docs frequently use the `.. include` directive to combine multiple .rst input files in one output file.
Sphinx builds each *included* .rst input file in addition to the referencing file(s).
These duplicate outpute files don't appear in the docs, because they are not included in any ToC.
However, the files _do_ appear in the search results.

On the one hand, this is a bit confusing.
On the other hand, it's slightly easier to navigate to a relevant search results when the `.. include` snippet files show up.

We could prevent Sphinx from building the duplicate files by configuring [exclude patterns](http://www.sphinx-doc.org/en/stable/config.html?#confval-exclude_patterns).

What do you think, @hilton ? :-)

**Comment by hilton** [comment]
Excellent suggestion. If possible, that would definitely be worth trying, because it would also clean up the build output, which reports warnings for the files that aren't in any TOC, and the duplicate IDs they contain.

The exclude patterns should probably just exclude all `.rst` files in a sub-directory. I can't tell from the docs if that means listing the sub-directories individually. Otherwise, we could add some suffix to the included file names, to make the exclude pattern simple.

**Comment by hilton** [comment]
Perhaps this would make the build faster too.

**Comment by TimKam** [comment]
Ok, I'll look into this.

**Comment by TimKam** [comment]
I needed to add a prefix (`include_`) to all folders that only contain 'included' files.
