### ISSUE TITLE
Resolve build warnings

### ISSUE THREAD

**Issue by hilton** [effektif/user-docs#171]
Resolve as many of the docs build warnings as possible:

- [x] _duplicate label_ (caused by duplicate `docs/` and `docs/en/` files)
- [x] _document isn't included in any toctree_ (for included files)
- …

**Comment by TimKam** [comment]
With the latest Sphinx release (1.4.9) the only warnings the English html build throws are _duplicate explicit target name_.
These appear if we define links with the same label within one document, for example

     `sales@signavio.com <mailto:sales@signavio.com?subject=Signavio%20Workflow%20Enterprise%20Cloud>`_

     `sales@signavio.com <mailto:sales@signavio.com?subject=Signavio%20Workflow%20Professional%20Cloud>`_

This is because standard hyperlinks automatically create a variable you can later reuse.
It's better to use [anonymous hyperlinks](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks) by simply appending a second underscore.

I suppose the warnings in the German build are typos. I'll fix all warnings soon and will change the Sphinx version that's specified in the requirements file.

**Comment by TimKam** [comment]
Ok, I could identify the reason for the _duplicate label_ issue (it only occurred on my machine after I did several rebuilds).
Seems the way the search results prettifier script handles the text build was the problem.
Using the extension I wrote for this a while ago fixed this problem for me.

*document isn't included in any toctree* shouldn't appear with the current Sphinx version since we specify:

```
exclude_patterns = [
    '_build',
    'include_*/*'
    ]
```
