### ISSUE TITLE
Search results : Link is not usable ( Search creates wrong link to document)

### ISSUE THREAD

**Issue by sonjahoyer** [effektif/user-docs#187]
Try:
http://docs.workflow.signavio.com/de/latest/search.html?q=API&check_keywords=yes&area=default

Click on
Custom data connectors ( for example)
http://docs.workflow.signavio.com/de/latest/integration/connectors.rst.html?highlight=api

then you get:
![search_swf](https://cloud.githubusercontent.com/assets/20281250/21451696/3de13148-c901-11e6-9848-c5b323af6bc0.JPG)

**Comment by hilton** [comment]
This seems to affect search results in German but not in English

**Comment by TimKam** [comment]
Two interesting findings:
* The English version is using RtD's own search, which works fine. Although RtD's search can handle requests for the German project, it isn't used in the German version of the docs.
* The default Sphinx search is bugged on RtD, which is probably a bug that's fixed in the latest Sphinx release.
It's not trivial to fix this issue because I don't fully control the build environment on RtD.

**Comment by TimKam** [comment]
See my comment at https://github.com/rtfd/readthedocs.org/issues/2427.

@sonjahoyer Did a customer report this?

**Comment by SilentGert** [comment]
No, Sonja found the issue while searching for some documentation chapter for a customer.

**Comment by TimKam** [comment]
Downgrading to an older Sphinx version fixes this issue.
Still, the search preview snippets are in raw markup and English :-(
It's pretty ugly but hard (perhaps impossible) to change for us.
RtD is currently improving their search, so let's hope they'll fix it soon.
Otherwise, the search snippet language/raw markup issue will be fixed once we move these docs to our own infrastructure.
