### ISSUE TITLE
Example processes: small glitches

### ISSUE THREAD

**Issue by TimKam** [effektif/user-docs#69]
- [x] The following sentence is probably not correct: _Staff may perform might be performed tasks sequentially in practice, even though they could perform them in parallel._
- [x] As mentioned in the pull request, the image of the process "approve vacation request" does not seem to fit the textual description of the process.
- [x] Just an idea: Wouldn't it be nice to make the example processes somewhere available, so users can import them?
- [x] Document the _Examples_ menu at the start of the examples chapter.

**Comment by hilton** [comment]
> The following sentence is probably not correct: Staff may perform might be performed tasks sequentially in practice, even though they could perform them in parallel.

Yep - fixed in https://github.com/effektif/user-docs/commit/2742eb3ecd2e443952655e84118f616eb46393d1

> Just an idea: Wouldn't it be nice to make the example processes somewhere available, so users can import them?

Yes, this is the plan, in general, and most of them are already available in the application under _Examples_. I should certainly update the chapter intro to mention that. I also still need to figure out how to publish the examples in the application more easily, so I can synchronise them with this new chapter.

**Comment by TimKam** [comment]
Great - just assign a ticket to me if I should provide the German versions of the example processes.
As for now, they are merely sketches.
